# Generated by Django 4.1.3 on 2022-11-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_num', models.SmallIntegerField(blank=True, default='Не определено', null=True, verbose_name='Номер хендла объекта')),
                ('obj_name', models.CharField(blank=True, default='Не определено', max_length=999, null=True, verbose_name='Имя объекта')),
                ('top_y', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Верхняя Y координата')),
                ('bottom_y', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Нижняя Y координата')),
                ('left_x', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Левая X координата')),
                ('right_x', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Правая X координата')),
            ],
        ),
    ]
